### ISSUE TITLE
Add ability to overide FDB5_CONFIG_FILE in python.

### ISSUE THREAD

**Issue by TomHodson** [ecmwf/pyfdb#12]
### Is your feature request related to a problem? Please describe.

I'm currently using code that looks like the below to overide the default fdb config file. Might it be useful to add the ability to overide the config directly in the call to `pyfdb.FDB()`?

```python
import os
from pathlib import Path

# Point the FDB Client on this machine to the remote by setting the config
p = Path("./config/fdb/client/remote.yaml")
assert p.exists()
os.environ["FDB5_CONFIG_FILE"] = str(p.absolute())

# Set some debug flags
os.environ["ECKIT_DEBUG"] = "1"
os.environ["FDB_DEBUG"] = "1"

import pyfdb 
fdb = pyfdb.FDB()
```

### Describe the solution you'd like

Something like
```python
import pyfdb 
fdb = pyfdb.FDB(dict(
    type = "remote"
    host = "x.x.x.x"
    port =  "7654"
    schema = "/etc/fdb/schema"
))
```

### Organisation

ECMWF

**Comment by geier1993** [comment]
Ah, I just noticed that this is related to the feature request I just opened #17 

Is there a difference between `FDB_HOME` and `FDB_CONFIG_FILE` ?
Will the path `FDB_HOME` just be appended by `$FDB_HOME/etc/fdb/config.yml` ?

**Comment by tlmquintino** [comment]
yes there is a difference between FDB_HOME and FDB_CONFIG_FILE.
The default location of the config file is defined relative to FDB_HOME which is itself defined by default to where the shared library is installed.

**Comment by simondsmart** [comment]
Note that the environment variable you are referring to should be FDB5_CONFIG_FILE (note the 5). It has a default value of ~fdb/etc/fdb/config.yaml - which is most usages is equivalent to ${FDB_HOME}/etc/fdb/config.yaml (although it also has a mechanism to find the config by search paths relative to LibFdb5.so).

I don't think that there is a conflict between issues #12 and #17. I would argue against the FDB object taking a dictionary, and rather make it a bit more pythonic, accepting a range of keyword arguments, such that we can construct a Config object from that dictionary. Note that in the C++ API, the FDB class already accepts a config object (as well as a number of userconfig arguments). We should do that in the Python API as well.

Note that the Config object already treats "fdb_home" as a special key in the config, and it could be easily modified to support accepting "config_path" as a special keyword as well, so that all works relatively cleanly.

**Comment by geier1993** [comment]
yes i noticed that fdb_home is read from the `Config` and expanded.

I'm not aware of a C API for the eckit::LocalConfiguration and I know introducing them is some bit of work. That's why I first requested this change, as a valid intermediate step.
Having some explicit keywords first and then passing through all keywords would not change behaviour.
